-- This file is for use with Corona(R) SDK
--
-- This file is automatically generated with PhysicsEdtior (http://physicseditor.de). Do not edit
--
-- Usage example:
--			local scaleFactor = 1.0
--			local physicsData = (require "shapedefs").physicsData(scaleFactor)
--			local shape = display.newImage("objectname.png")
--			physics.addBody( shape, physicsData:get("objectname") )
--

-- copy needed functions to local scope
local unpack = unpack
local pairs = pairs
local ipairs = ipairs

local M = {}

function M.physicsData(scale)
	local physics = { data =
	{ 
		
		["bg"] = {
                    
                    
                    
                    
                    {
                    pe_fixture_id = "", density = 2, friction = 0, bounce = 0, 
                    filter = { categoryBits = 0, maskBits = 0, groupIndex = 0 },
                    shape = {   -510, 210  ,  -510, -510  ,  60, -510  ,  60, 210  }
                    }
                    
                    
                    
		}
		
		, 
		["ground"] = {
                    
                    
                    
                    
                    {
                    pe_fixture_id = "", density = 1, friction = 0.1, bounce = 0.3, 
                    filter = { categoryBits = 1, maskBits = 2, groupIndex = 0 },
                    shape = {   574, -180  ,  -450, -180  ,  -286, -457  ,  -19, -483  ,  167, -478  ,  420, -437  ,  572, -329  }
                    }
                     ,
                    {
                    pe_fixture_id = "", density = 1, friction = 0.1, bounce = 0.3, 
                    filter = { categoryBits = 1, maskBits = 2, groupIndex = 0 },
                    shape = {   -286, -457  ,  -450, -180  ,  -450, -308  }
                    }
                     ,
                    {
                    pe_fixture_id = "", density = 1, friction = 0.1, bounce = 0.3, 
                    filter = { categoryBits = 1, maskBits = 2, groupIndex = 0 },
                    shape = {   378, -488  ,  420, -437  ,  223, -487  ,  281, -508  ,  321, -510  ,  349, -504  }
                    }
                     ,
                    {
                    pe_fixture_id = "", density = 1, friction = 0.1, bounce = 0.3, 
                    filter = { categoryBits = 1, maskBits = 2, groupIndex = 0 },
                    shape = {   -192, -502  ,  -158, -507  ,  -19, -483  ,  -286, -457  ,  -250, -481  }
                    }
                     ,
                    {
                    pe_fixture_id = "", density = 1, friction = 0.1, bounce = 0.3, 
                    filter = { categoryBits = 1, maskBits = 2, groupIndex = 0 },
                    shape = {   420, -437  ,  167, -478  ,  223, -487  }
                    }
                    
                    
                    
		}
		
	} }

        -- apply scale factor
        local s = scale or 1.0
        for bi,body in pairs(physics.data) do
                for fi,fixture in ipairs(body) do
                    if(fixture.shape) then
                        for ci,coordinate in ipairs(fixture.shape) do
                            fixture.shape[ci] = s * coordinate
                        end
                    else
                        fixture.radius = s * fixture.radius
                    end
                end
        end
	
	function physics:get(name)
		return unpack(self.data[name])
	end

	function physics:getFixtureId(name, index)
                return self.data[name][index].pe_fixture_id
	end
	
	return physics;
end

return M

